virtio-blk: add missing method doc in tests
Add missing doc comment in #[cfg(test)] Request::new() method to silence
the `missing_docs` rustc lint.

    error: missing documentation for an associated function
       --> virtio-blk/src/request.rs:278:9
        |
    278 | /         pub fn new(
    279 | |             request_type: RequestType,
    280 | |             data: Vec<(GuestAddress, u32)>,
    281 | |             sector: u64,
    282 | |             status_addr: GuestAddress,
    283 | |         ) -> Self {
        | |_________________^
        |
    note: the lint level is defined here
       --> virtio-blk/src/lib.rs:8:9
        |
    8   | #![deny(missing_docs)]
        |         ^^^^^^^^^^^^

Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>